"""add stats to parts

Revision ID: 5c5f602a7da7
Revises: 21f0c2f9b0ea
Create Date: 2025-08-16 16:23:17.026469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c5f602a7da7'
down_revision: Union[str, Sequence[str], None] = '21f0c2f9b0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('stats', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'parts', 'stats', ['stats'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'parts', type_='foreignkey')
    op.drop_column('parts', 'stats')
    # ### end Alembic commands ###
