"""renamed stats columns

Revision ID: 6ad9e0519a43
Revises: 5c5f602a7da7
Create Date: 2025-08-27 19:29:54.364851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ad9e0519a43'
down_revision: Union[str, Sequence[str], None] = '5c5f602a7da7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('minSta', sa.Integer(), nullable=True))
    op.add_column('stats', sa.Column('maxSta', sa.Integer(), nullable=True))
    op.drop_column('stats', 'maxStamina')
    op.drop_column('stats', 'minStamina')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('minStamina', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('stats', sa.Column('maxStamina', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('stats', 'maxSta')
    op.drop_column('stats', 'minSta')
    # ### end Alembic commands ###
